name: Continuous Integration
on:
  pull_request:
    branches: ["master"]
  push:
    branches: ["master"]
jobs:
  continuous-delivery:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    # needs: continuous-integration
    steps:
      # - name: Repo checkout
      #   uses: action/checkout@v4
      - name: Hatz Deploy
        uses: appleboy/ssh-action@master
        with:
          username: ${{ secrets.VPS_USER }}
          host: ${{ secrets.VPS_HOST }}
          password: ${{ secrets.VPS_PASS }}
          script: |
            cd ~/vyzion/_local
            bash ./deploy-fca-strapi.sh
